name: Release Workflow

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsqu'un push est effectué sur la branche principale (ou la branche que vous utilisez)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Publish Release
      uses: heremaps/gradle-release@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gradle_version: '7.2'  # Version de Gradle à utiliser
